config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "tasks", to: "tasks#index"

get "tasks/new", to: "tasks#new"

post "tasks", to: "tasks#create"

get "tasks/:id", to: "tasks#show", as: :task

get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

patch 'tasks/:id', to: 'tasks#update'

delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)

    task.save
    redirect_to task_path(task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title, 'Title: ' %>
  <%= f.text_field :title %>

  <%= f.label :details, 'Details: ' %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2><%= task.title %> <%= task.details %></h2>
  <%= link_to "Edit", edit_task_path(task) %>
  <%= link_to "Delete", task_path(task),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
  <p><%= task.completed %></p>

<% end %>

app/views/tasks/new.html.erb
<form action="<%= tasks_path %>" method="POST">

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <label for="title">Title: </label>
  <input type="text" id="title" name="task[title]">

  <label for="details">Details: </label>
  <input type="text" id="details" name="task[details]">

  <input type="submit" value="Create New Task">
</form>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>